### PR TITLE
Minor fix for undefined get_monitor_sound_loop

### PR DESCRIPTION
**Pull request by MarcBanyard**
Minor fix for undefined **get_monitor_sound_loop** shown in logs

### CODE REVIEW

**Comment by TheWitness** [comment]
Is this ready to go then?

**Comment by MarcBanyard** [comment]
Yeah all tested and working as it should be.
Do I need to update the changelog?

**Comment by TheWitness** [comment]
Might as well.

**Comment by TheWitness** [comment]
Unless you did already.  We are between releases, so, only if you missed it before.

**Pull request merged**
