### PR TITLE
New layout, new list view mode and bug fixes

### PR DESCRIPTION
**Pull request by netniV**
--- 2.3 ---
* feature: improved header/filter layout for more consistent view
* feature: Added List View mode
* issue: fixed issue where hosts where not always evaluated properly in render_perms()

### CODE REVIEW

**Comment by netniV** [comment]
Here is a screenshot showing the new layout:

screen shot 2018-02-23 at 22 39 29

**Comment by ikorzha** [comment]
Guys I am sorry after  I have applied the latest Github monitor version from trunk and Navgiate to Monitor TAB, it gets auto disabled, I have opened an issue#51 https://github.com/Cacti/plugin_monitor/issues/51 with error msg from log.

**Comment by netniV** [comment]
Right, that will be a version requirement.  I thought I'd put that into the INFO file, and I've just double checked that I did.  This leads to a new bug ... upgrading a plugin isn't checking the version requirements.  You need to have Cacti v1.1.35 to use the updated monitor as it relies on functionality from that.

**Comment by ikorzha** [comment]
netniV, thank you I just upgraded Cacti to v1.1.35 Monitor plugin now works.  However I do have new error msg in the log please take a look below:

Also acknowledge button is cut off partially.

acknowledge



2018/02/24  17:10:14 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 122  draw_page)(/plugins/monitor/monitor.php: 145  render_tree)(/plugins/monitor/monitor.php: 855  CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
--
2018/02/24 17:10:14 - ERROR PHP NOTICE in   Plugin 'monitor': Undefined variable: hosts in file:  /var/www/html/plugins/monitor/monitor.php  on line: 855

**Comment by netniV** [comment]
Have you monitored any hosts yet?  This may be a bug where you haven't set any to be monitored?

**Comment by netniV** [comment]
Forget that, spotted the bug.

**Comment by ikorzha** [comment]
Great can you create a pull request with the fix to test?

**Comment by netniV** [comment]
Done. #52

**Comment by ikorzha** [comment]
Sorry to report but I have Identified more error when Monitor "list view selected" and looks like 1 error per host, which is huge error log, just few msg below.


2018/02/25  22:33:46 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 122  draw_page)(/plugins/monitor/monitor.php: 145  render_tree)(/plugins/monitor/monitor.php: 961  render_host)(/plugins/monitor/monitor.php: 1082  render_host_list)(/plugins/monitor/monitor.php: 1379  CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)
--
2018/02/25 22:33:46 - ERROR PHP NOTICE in   Plugin 'monitor': Undefined variable: criticalities in file:  /var/www/html/plugins/monitor/monitor.php  on line: 1379
2018/02/25 22:33:46 - CMDPHP PHP ERROR NOTICE  Backtrace: (/plugins/monitor/monitor.php: 122  draw_page)(/plugins/monitor/monitor.php: 145  render_tree)(/plugins/monitor/monitor.php: 961  render_host)(/plugins/monitor/monitor.php: 1082  render_host_list)(/plugins/monitor/monitor.php: 1379  CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)

**Comment by netniV** [comment]
Apply this patch and see if it disappears:
```diff
diff --git a/monitor.php b/monitor.php
index d8962c0..452b1b5 100644
--- a/monitor.php
+++ b/monitor.php
@@ -1354,6 +1354,7 @@ function render_footer_list($hosts) {
 }

 function render_host_list($host) {
+       global $criticalities;
        if (!is_device_allowed($host['id'])) {
                return ;
        }
```

**Comment by ikorzha** [comment]
I have applied the patch, no more errors in the log. Can you please apply it to github version.

**Pull request merged**
